### PR TITLE
fixed a bug when used the function "in_array"

### PR DESCRIPTION
**Pull request by lineofsky2017**
I used your code to convert a PHP array to a `.toml` file, but when I used `TomlBuilder` class to build my `.toml` file, the program always threw the `DumpException`.
When my array included  the zero element, your expression return `true`, made program stop.
```
if (in_array($key, $this->keyListArryOfTables)) {
    throw new DumpException(
        sprintf('The table %s has already been defined as previous array of tables', $key)
    );
}
```
I debugged it and found this bug.[document of in_array](http://php.net/manual/en/function.in-array.php#91911)

I added the third param `true` in your code, I guessed it would always suit for your scene.
In that case, I could build my program easily.

Additionally, there were some mistakes in the code. For example, the variable `$this->keyListArryOfTables` was a `key=>value` array, so I thought `array_key_exists` would be more correct than `in_array`.
```
if (in_array($key, $this->keyListArryOfTables, true)) {
        throw new DumpException(
        sprintf('The table %s has already been defined as previous array of tables', $key)
    );
}
```

```
if (false == isset($this->keyListArryOfTables[$key])) {
        $this->keyListArryOfTables[$key] = 0;
        $this->addKeyToKeyList($key);
    } else {
        $counter = $this->keyListArryOfTables[$key] + 1;
        $this->keyListArryOfTables[$key] = $counter + 1;
}
```

### CODE REVIEW

**Comment by yosymfony** [comment]
Could you describe your use-case with an Toml example?

**Comment by lineofsky2017** [comment]
Please see my new PR.
In my branch `builder`, if you checkout the TomlBuiler.php to your vision `7c60cdf`, you will find the program throw the exception, You can easy debug it.
```
if (in_array($key, $this->keyListArryOfTables)) {
    var_dump($key);
    var_dump($this->keyListArryOfTables);
    var_dump(in_array($key, $this->keyListArryOfTables));
    var_dump(in_array($key, $this->keyListArryOfTables, true));
    throw new DumpException(
        sprintf('The table %s has already been defined as previous array of tables', $key)
    );
}
```
The output:
```
string(5) "a2.b1"
array(1) {
  'a2' =>
  int(0)
}
bool(true)
bool(false)
Fatal error: Uncaught Yosymfony\Toml\Exception\DumpException: The table a2.b1 has already been defined as previous array of tables in TomlBuilder.php on line 294
```

**Comment by yosymfony** [comment]
I just resolved your issue. The problem was I was looking for a key in the array values. I just committed that change. In a few days, I'll do a release.

**Comment by yosymfony** [comment]
It'll be fixed in v1.0.4

**Pull request closed without merging**
